name: calendar
description: "AI calendar for Orange Innovation Cup"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_local_notifications: ^9.1.7
  flutter_native_timezone_updated_gradle: ^2.0.3
  timezone: ^0.8.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  date_picker_timeline: ^1.2.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.2
  uuid: ^4.4.2
  image_picker: ^0.8.4+4
  l: ^4.0.2
  local_auth: ^2.2.0
  animate_do: ^3.3.4
  flare_flutter: ^3.0.2
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.4
  flutter_image_compress: ^2.3.0
  image: ^4.2.0
  fluttertoast: ^8.2.6
  flutter_image_editor: ^2.1.0
  image_cropper: 7.1.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo.png"
  adaptive_icon_background: "#00000000"


flutter:
  uses-material-design: true

  assets:
    - images/
